//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWebApplication.CalculatorService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CalculatorService.TCQ_CalculatorWebServiceSoap")]
    public interface TCQ_CalculatorWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TCQ_Add", ReplyAction="*")]
        int TCQ_Add(int firstNumber, int secondNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TCQ_Add", ReplyAction="*")]
        System.Threading.Tasks.Task<int> TCQ_AddAsync(int firstNumber, int secondNumber);
        
        // CODEGEN: Generating message contract since element name TCQ_GetCalculationsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TCQ_GetCalculations", ReplyAction="*")]
        CalculatorWebApplication.CalculatorService.TCQ_GetCalculationsResponse TCQ_GetCalculations(CalculatorWebApplication.CalculatorService.TCQ_GetCalculationsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TCQ_GetCalculations", ReplyAction="*")]
        System.Threading.Tasks.Task<CalculatorWebApplication.CalculatorService.TCQ_GetCalculationsResponse> TCQ_GetCalculationsAsync(CalculatorWebApplication.CalculatorService.TCQ_GetCalculationsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TCQ_GetCalculationsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TCQ_GetCalculations", Namespace="http://tempuri.org/", Order=0)]
        public CalculatorWebApplication.CalculatorService.TCQ_GetCalculationsRequestBody Body;
        
        public TCQ_GetCalculationsRequest() {
        }
        
        public TCQ_GetCalculationsRequest(CalculatorWebApplication.CalculatorService.TCQ_GetCalculationsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class TCQ_GetCalculationsRequestBody {
        
        public TCQ_GetCalculationsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TCQ_GetCalculationsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TCQ_GetCalculationsResponse", Namespace="http://tempuri.org/", Order=0)]
        public CalculatorWebApplication.CalculatorService.TCQ_GetCalculationsResponseBody Body;
        
        public TCQ_GetCalculationsResponse() {
        }
        
        public TCQ_GetCalculationsResponse(CalculatorWebApplication.CalculatorService.TCQ_GetCalculationsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TCQ_GetCalculationsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CalculatorWebApplication.CalculatorService.ArrayOfString TCQ_GetCalculationsResult;
        
        public TCQ_GetCalculationsResponseBody() {
        }
        
        public TCQ_GetCalculationsResponseBody(CalculatorWebApplication.CalculatorService.ArrayOfString TCQ_GetCalculationsResult) {
            this.TCQ_GetCalculationsResult = TCQ_GetCalculationsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TCQ_CalculatorWebServiceSoapChannel : CalculatorWebApplication.CalculatorService.TCQ_CalculatorWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TCQ_CalculatorWebServiceSoapClient : System.ServiceModel.ClientBase<CalculatorWebApplication.CalculatorService.TCQ_CalculatorWebServiceSoap>, CalculatorWebApplication.CalculatorService.TCQ_CalculatorWebServiceSoap {
        
        public TCQ_CalculatorWebServiceSoapClient() {
        }
        
        public TCQ_CalculatorWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TCQ_CalculatorWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TCQ_CalculatorWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TCQ_CalculatorWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int TCQ_Add(int firstNumber, int secondNumber) {
            return base.Channel.TCQ_Add(firstNumber, secondNumber);
        }
        
        public System.Threading.Tasks.Task<int> TCQ_AddAsync(int firstNumber, int secondNumber) {
            return base.Channel.TCQ_AddAsync(firstNumber, secondNumber);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CalculatorWebApplication.CalculatorService.TCQ_GetCalculationsResponse CalculatorWebApplication.CalculatorService.TCQ_CalculatorWebServiceSoap.TCQ_GetCalculations(CalculatorWebApplication.CalculatorService.TCQ_GetCalculationsRequest request) {
            return base.Channel.TCQ_GetCalculations(request);
        }
        
        public CalculatorWebApplication.CalculatorService.ArrayOfString TCQ_GetCalculations() {
            CalculatorWebApplication.CalculatorService.TCQ_GetCalculationsRequest inValue = new CalculatorWebApplication.CalculatorService.TCQ_GetCalculationsRequest();
            inValue.Body = new CalculatorWebApplication.CalculatorService.TCQ_GetCalculationsRequestBody();
            CalculatorWebApplication.CalculatorService.TCQ_GetCalculationsResponse retVal = ((CalculatorWebApplication.CalculatorService.TCQ_CalculatorWebServiceSoap)(this)).TCQ_GetCalculations(inValue);
            return retVal.Body.TCQ_GetCalculationsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CalculatorWebApplication.CalculatorService.TCQ_GetCalculationsResponse> CalculatorWebApplication.CalculatorService.TCQ_CalculatorWebServiceSoap.TCQ_GetCalculationsAsync(CalculatorWebApplication.CalculatorService.TCQ_GetCalculationsRequest request) {
            return base.Channel.TCQ_GetCalculationsAsync(request);
        }
        
        public System.Threading.Tasks.Task<CalculatorWebApplication.CalculatorService.TCQ_GetCalculationsResponse> TCQ_GetCalculationsAsync() {
            CalculatorWebApplication.CalculatorService.TCQ_GetCalculationsRequest inValue = new CalculatorWebApplication.CalculatorService.TCQ_GetCalculationsRequest();
            inValue.Body = new CalculatorWebApplication.CalculatorService.TCQ_GetCalculationsRequestBody();
            return ((CalculatorWebApplication.CalculatorService.TCQ_CalculatorWebServiceSoap)(this)).TCQ_GetCalculationsAsync(inValue);
        }
    }
}
